name: Build Raspberry Pi Image
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Run PIMOD
        uses: Nature40/pimod@v0.4.4
        with:
          pifile: builder.pifile